### ISSUE TITLE
Unused Import?

### ISSUE THREAD

**Issue by rmorshea** [QuantStack/ipyigv#11]
Looks like an unused import of `spectate`?

https://github.com/QuantStack/ipyigv/blob/3a97c8cae52c02df2288cd3f1a00cc2827c46391/ipyigv/options.py#L5

**Comment by marimeireles** [comment]
Hum! I missed that, I'll check thanks Ryan :)

**Comment by marimeireles** [comment]
Yep! Seems like it's unused, sorry for the ping.
I helped the owner of the repo implementing a part of the code that had it, but I think he opted for not using it!
This PR #12 should do it.
